version: '2'
services:
  loanexchange-postgresql:
    image: postgres:11.2
    # volumes:
    #     - ~/volumes/jhipster/LoanExchange/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=LoanExchange
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
